# Generated by Django 5.2 on 2025-05-01 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppAuth', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyUser',
        ),
    ]
